config/routes.rb
Travelschemer::Application.routes.draw do

  get "page/home"

  devise_for :users

  resources :trips  do
    resources :questions do
      resources :answers
    end
  end

   root :to => 'page#home'

end

app/models/question.rb
class Question < ActiveRecord::Base
  validates_presence_of :title, :message => 'is required'
  validates_presence_of :body, :message => 'is required'
  belongs_to :trip
  belongs_to :user
  has_many :answers

  attr_accessible :body, :title, :trip, :trip_id
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @trip = Trip.find(params[:trip_id])
    @questions = @trip.questions.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @trip = Trip.find(params[:trip_id])
    @question = @trip.questions.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @trip = Trip.find(params[:trip_id])
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @trip = Trip.find(params[:trip_id])
    @question = @trip.questions.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create

    @trip = current_user.trips.where("id = ?", params[:trip_id]).first

    @question = @trip.questions.create (params[:question])
    @question.user = current_user

    respond_to do |format|
      if @question.save
        format.html { redirect_to trip_question_url(@trip,@question), notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @trip = Trip.find(params[:trip_id])
       @question = @trip.questions.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to trip_question_url(@question.trip_id,@question), notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @trip_id = @question.trip_id
    @question.destroy

    respond_to do |format|
      format.html { redirect_to trip_questions_url(@trip_id) }
      format.json { head :no_content }
    end
  end
end

app/views/questions/_form.html.erb
<%= form_for([@trip, @question]) do |f| %>
    <fieldset>
      <legend><%=locals[:form_title]%></legend>
    <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-error"><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li class="text-error"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

        <%= f.label :title %>
        <%= f.text_field :title , {:placeholder=>"Ask a question", :class=>"span5"}  %>

        <%= f.label :body %>
        <%= f.text_area :body, {:placeholder=>"Give some context to the question", :class=>"span5"}%>

  <div class="actions">
    <%= f.submit :class=>"btn btn-primary" %>
  </div>
    </fieldset>
<% end %>

app/views/questions/_questions_list.html.erb
<table style="width:100%;">
  <tr>
    <th></th>


  </tr>

  <% questions.each do |question| %>
      <tr>

        <td><%= link_to question.title, trip_question_path(@trip, question) %></td>

  <% end %>
</table>

app/views/questions/edit.html.erb
<%= render 'form', :locals => {:form_title => "Edit a Question"}  %>

<%= link_to 'Show', trip_question_path(@trip.id, @question) %> |
<%= link_to 'Back', trip_questions_path(@trip) %>

app/views/questions/index.html.erb
<div class="span12"><%= link_to @trip.title, trip_path(@trip) %></div>
<h1>questions</h1>

<%= render :partial => 'questions_list', :locals => {:questions => @trip.questions}  %>

<br />

<%= link_to 'New Question', new_trip_question_path(@trip) %>

app/views/questions/new.html.erb
<%= render 'form' , :locals => {:form_title => "Ask a Question"}  %>

<%= link_to 'Back', trip_path(@trip) %>

app/views/questions/show.html.erb
<div class="row-fluid">

  <ul class="breadcrumb">
    <li><a href="#"><%= link_to @trip.title, trip_path(@trip) %> </a><span class="divider">/</span></li>
    <li class="active"><%= @question.title %></li>
  </ul>

</div>
<div class="row-fluid">
  <div class="span8">
    <div class="row-fluid">
    <% if !notice.nil? %>
        <div id="notice" class="text-success"><%= notice %></div>
    <% end %>
      </div>
    <div class="row-fluid">

    <h1 class="span12"><%= @question.title %></h1>
    </div>
    <div class="row-fluid">
    <div class="lead span12"><%= @question.body %></div>
     </div>
    <div class="row-fluid">
    <ul class="unstyled">
      <%= render @question.answers %>
    </ul>
      </div>
    <div class="row-fluid">
      <h3>Answer your friend's question</h3>
    </div>
    <div class="row-fluid">
    <div class="span12"><%= render "answers/form" %></div>
      </div>
    <div class="span8">
      <%= link_to 'Edit', edit_trip_question_path(@trip, @question) %> |
      <%= link_to 'Back', trip_path(@trip) %>
    </div>
  </div>
  <div class="span4">
    <h3>Stuff related to Question</h3>

  </div>
</div>