config/routes.rb
Travelschemer::Application.routes.draw do

  get "page/home"

  devise_for :users

  resources :trips  do
    resources :questions do
      resources :answers
    end
  end

   root :to => 'page#home'

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  validates_presence_of :title, :message => 'is required'
  validates_presence_of :body, :message => 'is required'
  validates_presence_of :user_id , :message => 'is required'
  has_many :questions
  belongs_to :user
  attr_accessible :body, :public, :title,:user_id
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index]
  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = current_user.trips.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
     @trip = current_user.trips.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create

    @trip = current_user.trips.new(params[:trip])

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = current_user.trips.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = current_user.trips.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end
end

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
    <fieldset>
      <legend><%=locals[:form_title]%></legend>
    <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-error"><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li class="text-error"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.label :title %>
    <%= f.text_field :title ,{:placeholder=>"Enter a trip title", :class=>"span5"} %>
    <span class="help-block">Enter a catchy title to attract help</span>


    <%= f.label :body %>
    <%= f.text_area :body,{:placeholder=>"Enter a description of your dream trip", :class=>"span5"} %>


    <label class="checkbox">
    <%= f.check_box :public,{:class=>"checkbox"}  %>  Publish
    </label>
    <span class="help-block">When you are ready to publish this out to the masses, check the publish</span>
  <div class="actions">
    <%= f.submit :class=>"btn btn-primary" %>
  </div>
    </fieldset>
<% end %>

app/views/trips/edit.html.erb
<%= render 'form', :locals => {:form_title => "Edit a trip"} %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h1>Listing trips</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Public</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trips.each do |trip| %>
  <tr>
    <td><%= trip.title %></td>
    <td><%= trip.body %></td>
    <td><%= trip.public %></td>
    <td><%= link_to 'Show', trip %></td>
    <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
    <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<%= render 'form', :locals => {:form_title => "Create a trip"} %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<div class="row-fluid">
  <div class="span8">
    <div class="row-fluid">
      <% if !notice.nil? %>
          <div id="notice" class="text-success"><%= notice %></div>
      <% end %>
      <h1 >
        <%= @trip.title %>
      </h1>
      </div>
    <div class="row-fluid">
      <div class="span9">
        <%= @trip.body %>
      </div>
      <div class="span8">
        <%= link_to 'Edit', edit_trip_path(@trip), {:class => "btn btn-secondary pull-right"} %>
      </div>
    </div>
    <div class="row-fluid">
    <div class="span9">
      <h3>Questions:</h3>
      <%= render :partial => '/questions/questions_list', :locals => {:questions => @trip.questions} %>
      <br/> <%= link_to 'Get trip advice', new_trip_question_path(@trip), {:class => 'btn btn-primary pull-right'} %>
    </div>
      </div>

  </div>
  <div class="span4">
    <h3>Other trips you may like</h3>
    <ul>
      <li>
        trip 1
      </li>
      <li>trip 2</li>
    </ul>
  </div>
</div>