config/routes.rb
Travelschemer::Application.routes.draw do

  get "page/home"

  devise_for :users

  resources :trips  do
    resources :questions do
      resources :answers
    end
  end

   root :to => 'page#home'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates_presence_of :body, :message => 'is required'
  has_one :question
  attr_accessible :body, :question_id
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index

    @trip = Trip.find(params[:trip_id])
    @question = @trip.questions.where("id = ?", params[:question_id]).first
    @answers = @question.answers.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @question = Question.find(params[:question_id])
    @trip = Trip.find(@question.trip_id)
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @question = Question.find(params[:question_id])
    @trip = Trip.find(@question.trip_id)
    @answer = @question.answers.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @question = Question.find(params[:question_id])
    @trip = Trip.find(@question.trip_id)
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @question = Question.find(params[:question_id])
    @trip = Trip.find(@question.trip_id)
    @answer = @question.answers.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to trip_question_url(@trip, @question), notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @question = Question.find(params[:question_id])
    @trip = Trip.find(@question.trip_id)
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to trip_question_url(@trip, @question), notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @question = Question.find(params[:question_id])
    @trip = Trip.find(@question.trip_id)
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to trip_question_url(@trip, @question) }
      format.json { head :no_content }
    end
  end
end

app/views/answers/_answer.html.erb
<li>
  <span class="span9"> <%= answer.body %></span>
  <span class="pull-right span3">
    <%= link_to 'Edit', edit_trip_question_answer_path(@trip, @question, answer) %>
    <%= link_to 'Destroy', trip_question_answer_path(@trip, @question, answer), method: :delete, data: {confirm: 'Are you sure?'} %>
  </span>
</li>

app/views/answers/_form.html.erb
<%  @answer = @question.answers.build if @answer.nil?%>
<%= form_for([@trip,@question,@answer]) do |f| %>
    <fieldset>
    <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-error"><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li class="text-error"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.text_area :body, {:placeholder=>"Help your friend, answer the question", :class=>"span12"}%>

  <div class="actions">
    <%= f.submit :class=>"btn btn-primary pull-right"%>
  </div>
  </fieldset>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', trip_question_answer_path(@trip,@question,@answer) %> |
<%= link_to 'Back', trip_question_answers_path(@trip,@question) %>

app/views/answers/index.html.erb
<div class="row-fluid">
<h1 class="span12">Listing answers</h1>

<ul class="unstyled span8">


      <%= render @answers %>

</ul>
  </div>
  <div class="row-fluid">
 <div class="span12">
<%= link_to 'New Answer', new_trip_question_answer_path(@trip, @question) %>
</div>

</div>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', trip_question_answers_path(@trip,@question) %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @answer.body %>
</p>


<%= link_to 'Edit', edit_trip_question_answer_path(@trip, @question,@answer) %> |
<%= link_to 'Back', trip_question_answers_path(@trip, @question) %>